apiVersion: v2
name: dashdot
description: A Helm chart to deploy dashdot for Kubernetes
home: https://oben01.github.io/charts/charts/dashdot/
type: application
version: 1.0.2
appVersion: v5.2.3
icon: https://raw.githubusercontent.com/oben01/charts/main/charts/dashdot/icon.svg
kubeVersion: ">=1.22.0-0"
keywords:
  - dashdot
  - dashboard
sources:
  - https://github.com/MauriceNino/dashdot
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: First import
    - kind: added
      description: add more env variables
    - kind: added
      description: update chart version
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/MauriceNino/dashdot
    - name: Chart Source
      url: https://github.com/oben01/charts/tree/main/charts/dashdot
