apiVersion: v2
name: dashdot
description: A Helm chart to deploy dashdot for Kubernetes
home: https://oben01.github.io/charts/charts/dashdot/
type: application
version: 1.0.7
# renovate datasource=docker depName=ghcr.io/mauricenino/dashdot
appVersion: v5.8.3
icon: https://raw.githubusercontent.com/oben01/charts/main/charts/dashdot/icon.svg
kubeVersion: ">=1.22.0-0"
keywords:
  - dashdot
  - dashboard
sources:
  - https://github.com/MauriceNino/dashdot
annotations:
  artifacthub.io/signKey: |
    fingerprint: FA3F63F603B62356663A88F073AE49623786E060
    url: https://oben01.github.io/charts/pgp_keys.asc
  artifacthub.io/changes: |-
    - kind: fixed
      description: fix used of ingressClassName
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/MauriceNino/dashdot
    - name: Chart Source
      url: https://github.com/oben01/charts/tree/main/charts/dashdot
